# Generated by Django 5.0.6 on 2024-05-28 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makanan', '0002_alter_kategori_options_alter_menus_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menus',
            name='nama',
        ),
    ]
