# Generated by Django 5.0.6 on 2024-05-29 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makanan', '0004_rename_kategori_kategory_alter_kategory_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kategory',
            new_name='Kategori',
        ),
        migrations.RenameField(
            model_name='menus',
            old_name='kategori',
            new_name='kategory',
        ),
    ]
