# Generated by Django 5.0.6 on 2024-05-29 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makanan', '0005_rename_kategory_kategori_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menus',
            name='kategory',
        ),
        migrations.DeleteModel(
            name='Kategori',
        ),
    ]
