# Generated by Django 5.0.6 on 2024-05-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makanan', '0006_remove_menus_kategory_delete_kategori'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menus',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Menus'},
        ),
        migrations.AlterField(
            model_name='menus',
            name='menu',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
