# Generated by Django 5.0.6 on 2024-05-30 06:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makanan', '0007_alter_menus_options_alter_menus_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='deskripsi',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
