# Generated by Django 5.0.6 on 2024-05-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makanan', '0009_alter_menus_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/menu/'),
        ),
    ]
